name: Trigger

on:
  push:

env:
  PR_NUMBER: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo strawberries in target repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sckott/target/dispatches \
            -d '{
              "event_type":"dispatch-event",
              "client_payload": {
                "sha": "${{ github.sha }}",
                "ref": "${{ github.ref }}",
                "pr": "$PR_NUMBER"
              }
            }'
