name: Trigger

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: test stuff
        run: |
          SHA_DEPLOYED=$(curl \
            https://proof-api-dev.fredhutch.org/info | \
            jq .commit_sha)
          echo SHA_DEPLOYED: $SHA_DEPLOYED
          echo SHA: ${{ github.sha }}
      - name: Echo strawberries in target repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sckott/target/dispatches \
            -d '{
              "event_type":"dispatch-event",
              "client_payload": {
                "sha": "${{ github.sha }}",
                "ref": "${{ github.ref }}",
                "pr": "${{ github.event.issue.number }}"
              }
            }'
